import type { User, Product, Booking, Category, Notification, PriceRule, InventoryItem } from "./types"

// Change the dummy password to something secure that won't trigger breach warnings
export const DUMMY_PASSWORD = "RentalPro@2024#Secure"

export const DUMMY_USERS: User[] = [
  {
    id: "1",
    email: "admin@rental.com",
    name: "Admin User",
    role: "admin",
    verified: true,
    createdAt: "2024-01-01T00:00:00Z",
    phone: "+91 9876543210",
    address: "123 Admin Street, Business District",
  },
  {
    id: "2",
    email: "customer@rental.com",
    name: "John Customer",
    role: "customer",
    verified: true,
    createdAt: "2024-01-02T00:00:00Z",
    phone: "+91 9876543211",
    address: "456 Customer Lane, Residential Area",
  },
  {
    id: "3",
    email: "staff@rental.com",
    name: "Jane Staff",
    role: "staff",
    verified: true,
    createdAt: "2024-01-03T00:00:00Z",
    phone: "+91 9876543212",
    address: "789 Staff Road, Service Center",
  },
  {
    id: "4",
    email: "manager@rental.com",
    name: "Mike Manager",
    role: "staff",
    verified: true,
    createdAt: "2024-01-04T00:00:00Z",
    phone: "+91 9876543213",
    address: "321 Manager Avenue, Operations Hub",
  },
]

export const CATEGORIES: Category[] = [
  {
    id: "1",
    name: "Electronics",
    description: "Cameras, laptops, audio equipment, and more",
    image: "/placeholder.svg?height=200&width=300&text=Electronics",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "2",
    name: "Sports & Recreation",
    description: "Bikes, sports equipment, outdoor gear",
    image: "/placeholder.svg?height=200&width=300&text=Sports",
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "3",
    name: "Audio & Visual",
    description: "Sound systems, projectors, lighting equipment",
    image: "/placeholder.svg?height=200&width=300&text=Audio+Visual",
    isActive: true,
    sortOrder: 3,
  },
  {
    id: "4",
    name: "Outdoor & Camping",
    description: "Tents, camping gear, adventure equipment",
    image: "/placeholder.svg?height=200&width=300&text=Outdoor",
    isActive: true,
    sortOrder: 4,
  },
  {
    id: "5",
    name: "Tools & Equipment",
    description: "Power tools, construction equipment, machinery",
    image: "/placeholder.svg?height=200&width=300&text=Tools",
    isActive: true,
    sortOrder: 5,
  },
  {
    id: "6",
    name: "Party & Events",
    description: "Tables, chairs, decorations, catering equipment",
    image: "/placeholder.svg?height=200&width=300&text=Party+Events",
    isActive: true,
    sortOrder: 6,
  },
]

export const DUMMY_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Premium DSLR Camera Kit",
    description:
      "Professional Canon EOS R5 with multiple lenses, tripod, and accessories. Perfect for photography and videography projects.",
    category: "Electronics",
    subcategory: "Cameras",
    images: [
      "/placeholder.svg?height=400&width=600&text=DSLR+Camera+Kit",
      "/placeholder.svg?height=400&width=600&text=Camera+Lens+1",
      "/placeholder.svg?height=400&width=600&text=Camera+Lens+2",
      "/placeholder.svg?height=400&width=600&text=Camera+Accessories",
    ],
    basePrice: 150,
    unit: "day",
    stock: 8,
    totalStock: 10,
    amenities: ["64GB Memory Card", "Professional Tripod", "Extra Battery Pack", "Carrying Case", "Lens Cleaning Kit"],
    specifications: {
      Sensor: "45MP Full Frame",
      Video: "8K RAW Recording",
      "ISO Range": "100-51200",
      "Lens Mount": "Canon RF",
      Weight: "650g (body only)",
    },
    notes: "Handle with extreme care. Professional training recommended. Insurance required for rentals over 7 days.",
    isRentable: true,
    popularity: 95,
    rating: 4.8,
    reviewCount: 124,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
    tags: ["professional", "photography", "videography", "canon", "full-frame"],
    location: "Warehouse A - Section 1",
    condition: "excellent",
    maintenanceSchedule: "Monthly",
    lastMaintenance: "2024-01-10T00:00:00Z",
    qrCode: "QR001",
  },
  {
    id: "2",
    name: "Mountain Bike - Trek X-Caliber",
    description:
      "High-performance mountain bike perfect for trails, city rides, and adventures. Features 29-inch wheels and 21-speed transmission.",
    category: "Sports & Recreation",
    subcategory: "Bicycles",
    images: [
      "/placeholder.svg?height=400&width=600&text=Mountain+Bike",
      "/placeholder.svg?height=400&width=600&text=Bike+Details",
      "/placeholder.svg?height=400&width=600&text=Bike+Accessories",
    ],
    basePrice: 40,
    unit: "day",
    stock: 15,
    totalStock: 20,
    amenities: ["Safety Helmet", "Water Bottle", "Repair Kit", "Lock", "Reflective Vest"],
    specifications: {
      "Frame Size": "Medium (17.5 inches)",
      "Wheel Size": "29 inches",
      Gears: "21-speed Shimano",
      Weight: "13.5 kg",
      "Max Rider Weight": "120 kg",
    },
    notes: "Helmet mandatory. Basic cycling knowledge required. Check tire pressure before each ride.",
    isRentable: true,
    popularity: 88,
    rating: 4.6,
    reviewCount: 89,
    createdAt: "2024-01-02T00:00:00Z",
    updatedAt: "2024-01-14T00:00:00Z",
    tags: ["mountain-bike", "trek", "outdoor", "adventure", "cycling"],
    location: "Warehouse B - Bike Section",
    condition: "excellent",
    maintenanceSchedule: "Weekly",
    lastMaintenance: "2024-01-12T00:00:00Z",
    qrCode: "QR002",
  },
  {
    id: "3",
    name: "Professional Sound System",
    description:
      "Complete PA system with wireless microphones, mixer, and powerful speakers. Ideal for events, parties, and presentations.",
    category: "Audio & Visual",
    subcategory: "Sound Systems",
    images: [
      "/placeholder.svg?height=400&width=600&text=Sound+System",
      "/placeholder.svg?height=400&width=600&text=Mixer+Console",
      "/placeholder.svg?height=400&width=600&text=Wireless+Mics",
      "/placeholder.svg?height=400&width=600&text=Speakers",
    ],
    basePrice: 200,
    unit: "day",
    stock: 5,
    totalStock: 8,
    amenities: ["2x Wireless Microphones", "Bluetooth Connectivity", "LED Light Effects", "All Cables", "Setup Guide"],
    specifications: {
      "Power Output": "1000W RMS",
      "Frequency Response": "20Hz - 20kHz",
      Connectivity: "Bluetooth, USB, XLR, 1/4 inch",
      Microphones: "2x Wireless + 4x Wired inputs",
      Coverage: "Up to 500 people",
    },
    notes:
      "Professional setup available for additional fee. Noise regulations must be followed. Damage deposit required.",
    isRentable: true,
    popularity: 92,
    rating: 4.7,
    reviewCount: 67,
    createdAt: "2024-01-03T00:00:00Z",
    updatedAt: "2024-01-13T00:00:00Z",
    tags: ["sound-system", "pa", "wireless", "events", "professional"],
    location: "Warehouse A - Audio Section",
    condition: "excellent",
    maintenanceSchedule: "Bi-weekly",
    lastMaintenance: "2024-01-08T00:00:00Z",
    qrCode: "QR003",
  },
  {
    id: "4",
    name: "4-Person Camping Tent",
    description: "Waterproof family camping tent with easy setup. Perfect for weekend getaways and outdoor adventures.",
    category: "Outdoor & Camping",
    subcategory: "Tents",
    images: [
      "/placeholder.svg?height=400&width=600&text=Camping+Tent",
      "/placeholder.svg?height=400&width=600&text=Tent+Interior",
      "/placeholder.svg?height=400&width=600&text=Tent+Setup",
    ],
    basePrice: 30,
    unit: "day",
    stock: 12,
    totalStock: 15,
    amenities: ["4x Sleeping Bags", "Ground Tarp", "Setup Instructions", "Tent Stakes", "Repair Kit"],
    specifications: {
      Capacity: "4 persons",
      Dimensions: "3m x 2.5m x 1.8m",
      Weight: "8.5 kg",
      Material: "Ripstop Polyester",
      "Waterproof Rating": "3000mm",
    },
    notes: "Check weather conditions before use. Clean and dry before return. Setup video available online.",
    isRentable: true,
    popularity: 75,
    rating: 4.4,
    reviewCount: 45,
    createdAt: "2024-01-04T00:00:00Z",
    updatedAt: "2024-01-12T00:00:00Z",
    tags: ["camping", "tent", "outdoor", "family", "waterproof"],
    location: "Warehouse C - Outdoor Section",
    condition: "good",
    maintenanceSchedule: "After each rental",
    lastMaintenance: "2024-01-11T00:00:00Z",
    qrCode: "QR004",
  },
  {
    id: "5",
    name: "Power Drill Set - DeWalt",
    description:
      "Professional cordless drill set with multiple bits and accessories. Perfect for DIY projects and construction work.",
    category: "Tools & Equipment",
    subcategory: "Power Tools",
    images: [
      "/placeholder.svg?height=400&width=600&text=Power+Drill+Set",
      "/placeholder.svg?height=400&width=600&text=Drill+Bits",
      "/placeholder.svg?height=400&width=600&text=Tool+Case",
    ],
    basePrice: 25,
    unit: "day",
    stock: 20,
    totalStock: 25,
    amenities: ["50+ Drill Bits", "2x Batteries", "Charger", "Carrying Case", "Safety Glasses"],
    specifications: {
      Voltage: "20V MAX",
      "Chuck Size": "1/2 inch",
      Torque: "650 in-lbs",
      "Battery Life": "Up to 4 hours",
      Weight: "1.8 kg",
    },
    notes: "Safety equipment mandatory. Basic tool knowledge required. Report any damage immediately.",
    isRentable: true,
    popularity: 82,
    rating: 4.5,
    reviewCount: 78,
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-11T00:00:00Z",
    tags: ["power-tools", "dewalt", "drill", "construction", "diy"],
    location: "Warehouse D - Tools Section",
    condition: "excellent",
    maintenanceSchedule: "Monthly",
    lastMaintenance: "2024-01-09T00:00:00Z",
    qrCode: "QR005",
  },
  {
    id: "6",
    name: "Party Table & Chair Set",
    description:
      "Complete party furniture set with round tables and comfortable chairs. Perfect for events and celebrations.",
    category: "Party & Events",
    subcategory: "Furniture",
    images: [
      "/placeholder.svg?height=400&width=600&text=Party+Tables",
      "/placeholder.svg?height=400&width=600&text=Party+Chairs",
      "/placeholder.svg?height=400&width=600&text=Event+Setup",
    ],
    basePrice: 15,
    unit: "day",
    stock: 30,
    totalStock: 40,
    amenities: ["Table Cloths", "Chair Covers", "Setup Service", "Pickup Service", "Cleaning Included"],
    specifications: {
      "Table Size": "6 feet round",
      Seating: "8 persons per table",
      Material: "Plastic/Metal",
      "Weight Capacity": "150 kg per chair",
      "Color Options": "White, Black",
    },
    notes: "Delivery and setup available. Minimum order 5 sets. Clean return required.",
    isRentable: true,
    popularity: 70,
    rating: 4.3,
    reviewCount: 34,
    createdAt: "2024-01-06T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
    tags: ["party", "furniture", "tables", "chairs", "events"],
    location: "Warehouse E - Event Section",
    condition: "good",
    maintenanceSchedule: "After each rental",
    lastMaintenance: "2024-01-09T00:00:00Z",
    qrCode: "QR006",
  },
]

export const DUMMY_BOOKINGS: Booking[] = [
  {
    id: "1",
    customerId: "2",
    customerName: "John Customer",
    customerEmail: "customer@rental.com",
    customerPhone: "+91 9876543211",
    productId: "1",
    productName: "Premium DSLR Camera Kit",
    startDate: "2024-01-20T10:00:00Z",
    endDate: "2024-01-23T10:00:00Z",
    quantity: 1,
    basePrice: 450,
    discountAmount: 45,
    taxAmount: 40.5,
    totalPrice: 445.5,
    status: "confirmed",
    paymentStatus: "paid",
    paymentAmount: 445.5,
    createdAt: "2024-01-15T12:00:00Z",
    updatedAt: "2024-01-15T12:00:00Z",
    notes: "Wedding photography project",
    pickupLocation: "Main Store",
    returnLocation: "Main Store",
    staffAssigned: "3",
    securityDeposit: 1000,
  },
  {
    id: "2",
    customerId: "2",
    customerName: "John Customer",
    customerEmail: "customer@rental.com",
    customerPhone: "+91 9876543211",
    productId: "2",
    productName: "Mountain Bike - Trek X-Caliber",
    startDate: "2024-01-25T09:00:00Z",
    endDate: "2024-01-27T09:00:00Z",
    quantity: 2,
    basePrice: 160,
    discountAmount: 0,
    taxAmount: 14.4,
    totalPrice: 174.4,
    status: "picked-up",
    paymentStatus: "paid",
    paymentAmount: 174.4,
    createdAt: "2024-01-22T10:00:00Z",
    updatedAt: "2024-01-25T09:00:00Z",
    notes: "Weekend cycling trip",
    pickupLocation: "Main Store",
    returnLocation: "Main Store",
    staffAssigned: "3",
    securityDeposit: 500,
  },
  {
    id: "3",
    customerId: "4",
    customerName: "Mike Manager",
    customerEmail: "manager@rental.com",
    customerPhone: "+91 9876543213",
    productId: "3",
    productName: "Professional Sound System",
    startDate: "2024-01-30T14:00:00Z",
    endDate: "2024-01-30T23:00:00Z",
    quantity: 1,
    basePrice: 200,
    discountAmount: 20,
    taxAmount: 16.2,
    totalPrice: 196.2,
    status: "pending",
    paymentStatus: "partial",
    paymentAmount: 100,
    createdAt: "2024-01-28T15:00:00Z",
    updatedAt: "2024-01-28T15:00:00Z",
    notes: "Corporate event",
    pickupLocation: "Main Store",
    returnLocation: "Main Store",
    securityDeposit: 2000,
  },
]

export const DUMMY_NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    userId: "1",
    title: "Low Stock Alert",
    message: "Mountain Bike stock is running low (5 units remaining)",
    type: "warning",
    isRead: false,
    createdAt: "2024-01-15T10:00:00Z",
    actionUrl: "/admin/inventory",
  },
  {
    id: "2",
    userId: "1",
    title: "New Booking",
    message: "New booking received for Professional Sound System",
    type: "info",
    isRead: false,
    createdAt: "2024-01-15T09:30:00Z",
    actionUrl: "/admin/bookings",
  },
  {
    id: "3",
    userId: "2",
    title: "Booking Confirmed",
    message: "Your booking for DSLR Camera Kit has been confirmed",
    type: "success",
    isRead: true,
    createdAt: "2024-01-15T08:00:00Z",
    actionUrl: "/customer/bookings",
  },
]

export const DUMMY_PRICE_RULES: PriceRule[] = [
  {
    id: "1",
    name: "Weekend Discount",
    description: "10% off on weekend bookings",
    discountType: "percentage",
    discountValue: 10,
    customerGroup: "all",
    validFrom: "2024-01-01T00:00:00Z",
    validTo: "2024-12-31T23:59:59Z",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Bulk Booking Discount",
    description: "15% off for bookings of 5+ items",
    discountType: "percentage",
    discountValue: 15,
    customerGroup: "all",
    minQuantity: 5,
    validFrom: "2024-01-01T00:00:00Z",
    validTo: "2024-12-31T23:59:59Z",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "VIP Customer Discount",
    description: "20% off for VIP customers",
    discountType: "percentage",
    discountValue: 20,
    customerGroup: "vip",
    validFrom: "2024-01-01T00:00:00Z",
    validTo: "2024-12-31T23:59:59Z",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
]

export const DUMMY_INVENTORY: InventoryItem[] = [
  {
    id: "1",
    productId: "1",
    serialNumber: "CAM001",
    condition: "excellent",
    status: "available",
    location: "Warehouse A - Section 1 - Shelf 3",
    purchaseDate: "2023-06-15T00:00:00Z",
    purchasePrice: 25000,
    currentValue: 22000,
    lastMaintenance: "2024-01-10T00:00:00Z",
    nextMaintenance: "2024-02-10T00:00:00Z",
    notes: "Regular maintenance completed",
  },
  {
    id: "2",
    productId: "1",
    serialNumber: "CAM002",
    condition: "excellent",
    status: "rented",
    location: "Out for rental",
    purchaseDate: "2023-06-15T00:00:00Z",
    purchasePrice: 25000,
    currentValue: 22000,
    lastMaintenance: "2024-01-05T00:00:00Z",
    nextMaintenance: "2024-02-05T00:00:00Z",
    notes: "Currently with customer John",
  },
  {
    id: "3",
    productId: "2",
    serialNumber: "BIKE001",
    condition: "good",
    status: "available",
    location: "Warehouse B - Bike Section - Rack 1",
    purchaseDate: "2023-08-20T00:00:00Z",
    purchasePrice: 15000,
    currentValue: 12000,
    lastMaintenance: "2024-01-12T00:00:00Z",
    nextMaintenance: "2024-01-19T00:00:00Z",
    notes: "Tire pressure checked",
  },
]

// Add payment-related data structures
export interface PaymentMethod {
  id: string
  name: string
  type: "online" | "cash"
  description: string
  isActive: boolean
  processingFee?: number
}

export const PAYMENT_METHODS: PaymentMethod[] = [
  {
    id: "razorpay",
    name: "Razorpay",
    type: "online",
    description: "Pay securely with cards, UPI, wallets",
    isActive: true,
    processingFee: 2.5,
  },
  {
    id: "cash",
    name: "Cash on Delivery",
    type: "cash",
    description: "Pay cash during pickup",
    isActive: true,
    processingFee: 0,
  },
]
